#!/bin/bash
var=$1
mkdir -p /home/dino/Desktop/Chemistry/SimulationResults/$var/
cp main.cpp /home/dino/Desktop/Chemistry/SimulationResults/$var/
g++ -fopenmp main.cpp -o /home/dino/Desktop/Chemistry/SimulationResults/$var/angron
