#!/bin/bash
var=$1
mkdir -p /home/dino/Desktop/Chemistry/SimulationResults/$var/
cp maintest.cpp /home/dino/Desktop/Chemistry/SimulationResults/$var/
g++ main.cpp -o /home/dino/Desktop/Chemistry/SimulationResults/$var/angron
